### ISSUE TITLE
Ajout proba shinny sur la page info

### ISSUE THREAD

**Issue by Gacara** [Gacara/shasser#9]
Summary
Ajout des informations des taux d'apparitions des shiny en fonction du nombre de pokemon rencontrés et de l'acquisition de l'objet Charme Chroma
###TODO

- [x] Affichage des taux d'apparitions sous forme de tableau

- [x] Mise à jour des probabilités en fonction du compteur

- [x] Ajout de l'objet charme chroma sous forme de toggle et mise à jour des probabilités

- [x] Sauvegarde dans la base de données et récupération de l'état de l'objet
